-- 새 계정 생성
CREATE USER SCOTT2 IDENTIFIED BY 1111
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- 새로 생성한 계정에 권한 부여
GRANT CONNECT, RESOURCE, DBA TO scott2;

-- 기존에 있는 계정에 권한 부여하고 table space 지정
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO SCOTT IDENTIFIED BY TIGER;
ALTER USER SCOTT DEFAULT TABLESPACE USERS;
ALTER USER SCOTT TEMPORARY TABLESPACE TEMP;
CONNECT SCOTT/TIGER
GRANT CONNECT,  

-- 비밀번호 변경
ALTER USER SCOTT IDENTIFIED BY 1111;

-- 새 계정 생성하기 (tjoeun)
CREATE USER TJOEUN IDENTIFIED by 1111
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- 권한 부여하기
GRANT CONNECT, RESOURCE, DBA TO TJOEUN;


